a = ("the quick brown fox jumps over the lazy dog.")
print(a.capitalize())
b = ("the quick brown fox jumps over the lazy dog.")
print(b.upper())
c = ("the quick brown fox jumps over the lazy dog.")
print(c.split(maxsplit=1))
d = ("the quick brown fox jumps over the lazy dog.")
print(d.title())
e = ("THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.")
print(e.swapcase())
f = ("www.the quick brown fox jumps over the lazy dog.com")
print(f.strip('cwww.om'))
g = ("the quick brown fox jumps over the lazy dog.")
print(g.splitlines(keepends=True))
h = ("the quick brown fox jumps over the lazy dog.")
print(h.split())
i = ("nigeria")
print(i.rstrip('ia'))
j = ("the quick brown fox jumps over the lazy dog.")
print(j.rfind('z'))
k = ("the quick brown fox jumps over the lazy dog.")
print(k.rindex('w'))
l = ("the quick brown fox jumps over the lazy dog.")
print(l.replace('dog', 'cat'))
m = ("the quick brown fox jumps over the lazy dog.")
print(m.islower())
n = ("THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.")
print(n.isupper())
o = ("the quick brown fox jumps over the lazy dog.")
print(o.join(("the")))